-- Generated by nwg-displays on 2026-06-08 at 12:26:47. Do not edit manually.

hl.monitor({
    output = "desc:Sharp Corporation 0x1593",
    mode = "1920x1200@120.0",
    position = "0x0",
    scale = 1.0
})
