windowrule = match:initial_class float, match:class = rofi

windowrule = fullscreen_state 0 2, match:class firefox-developer-edition

windowrule {
    name = sysmon-float
    match:class = org.gnome.SystemMonitor
    float = on
    size = 1200 800
    center = on
}


#windowrule = tile, class:ghidra-Ghidra
# windowrule = match:initial_class tile, match:class = autopsy

#windowrulev2 = move cursor,class:REAPER,floating:1
#windowrulev2 = nofocus,class:REAPER,title:^(menu)$
#windowrulev2 = nofocus,class:REAPER,title:^$
